In [1]:
import pandas as pd

In [2]:
data= pd.read_csv("data clean.csv")

In [3]:
data

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

In [4]:
data.shape

(158, 10)

In [9]:
data.isna().sum()

Unnamed: 0    0
Ozone         0
Solar.R       7
Wind          0
Temp C        0
Month         0
Day           0
Year          0
Temp          0
Weather       3
dtype: int64

In [17]:
data_1=data.drop(columns="Unnamed: 0")

In [8]:
data["Ozone"]=data["Ozone"].fillna(data["Ozone"].mean())

In [18]:
data_1

         Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0    41.000000    190.0   7.4     67     5    1  2010    67       S
1    36.000000    118.0   8.0     72     5    2  2010    72       C
2    12.000000    149.0  12.6     74     5    3  2010    74      PS
3    18.000000    313.0  11.5     62     5    4  2010    62       S
4    41.583333      NaN  14.3     56     5    5  2010    56       S
..         ...      ...   ...    ...   ...  ...   ...   ...     ...
153  41.000000    190.0   7.4     67     5    1  2010    67       C
154  30.000000    193.0   6.9     70     9   26  2010    70      PS
155  41.583333    145.0  13.2     77     9   27  2010    77       S
156  14.000000    191.0  14.3     75     9   28  2010    75       S
157  18.000000    131.0   8.0     76     9   29  2010    76       C

[158 rows x 9 columns]

In [19]:
data_1["Solar.R"]=data_1["Solar.R"].fillna(data_1["Solar.R"].median())

In [35]:
data_1["Month"].unique()

array(['5', 5, '6', '7', '8', '9'], dtype=object)

In [34]:
data_1["Month"]=data_1["Month"].replace(to_replace="May",value='5')

In [37]:
data_1["Month"]=pd.to_numeric(data_1["Month"])

In [48]:
data_1.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather      int64
dtype: object

In [39]:
data_1=data_1.drop(columns="Temp C")

In [41]:
data_2=data_1.copy()

In [42]:
data_2

         Ozone  Solar.R  Wind  Month  Day  Year  Temp Weather
0    41.000000    190.0   7.4      5    1  2010    67       S
1    36.000000    118.0   8.0      5    2  2010    72       C
2    12.000000    149.0  12.6      5    3  2010    74      PS
3    18.000000    313.0  11.5      5    4  2010    62       S
4    41.583333    197.0  14.3      5    5  2010    56       S
..         ...      ...   ...    ...  ...   ...   ...     ...
153  41.000000    190.0   7.4      5    1  2010    67       C
154  30.000000    193.0   6.9      9   26  2010    70      PS
155  41.583333    145.0  13.2      9   27  2010    77       S
156  14.000000    191.0  14.3      9   28  2010    75       S
157  18.000000    131.0   8.0      9   29  2010    76       C

[158 rows x 8 columns]

In [43]:
from sklearn.preprocessing import LabelEncoder as Le

In [44]:
Le=Le()

In [46]:
Le.fit_transform(data_2["Weather"])

array([2, 0, 1, 2, 2, 0, 1, 0, 1, 2, 0, 1, 2, 2, 0, 2, 2, 0, 1, 2, 2, 0,
       1, 0, 1, 0, 1, 2, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2,
       2, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 2,
       0, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 2, 0, 1, 0, 2, 2, 0, 1, 1, 0, 3,
       2, 0, 1, 0, 1, 3, 1, 3, 2, 0, 0, 1, 0, 1, 2, 2, 2, 0, 0, 0, 1, 0,
       1, 2, 2, 0, 1, 0, 1, 2, 2, 2, 2, 2, 0, 0, 1, 0, 1, 2, 2, 2, 0, 1,
       0, 1, 2, 2, 1, 1, 2, 1, 2, 0, 1, 1, 2, 2, 0, 1, 0, 1, 2, 1, 2, 0,
       1, 2, 2, 0])

In [47]:
data_1["Weather"]=Le.fit_transform(data_1["Weather"])

In [49]:
data_1

         Ozone  Solar.R  Wind  Month  Day  Year  Temp  Weather
0    41.000000    190.0   7.4      5    1  2010    67        2
1    36.000000    118.0   8.0      5    2  2010    72        0
2    12.000000    149.0  12.6      5    3  2010    74        1
3    18.000000    313.0  11.5      5    4  2010    62        2
4    41.583333    197.0  14.3      5    5  2010    56        2
..         ...      ...   ...    ...  ...   ...   ...      ...
153  41.000000    190.0   7.4      5    1  2010    67        0
154  30.000000    193.0   6.9      9   26  2010    70        1
155  41.583333    145.0  13.2      9   27  2010    77        2
156  14.000000    191.0  14.3      9   28  2010    75        2
157  18.000000    131.0   8.0      9   29  2010    76        0

[158 rows x 8 columns]

In [50]:
data_1["Weather"]=data_1["Weather"].fillna(data_1["Weather"].mode())

In [51]:
data_1.isna().sum()

Ozone      0
Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64